- hosts: '*'
  roles:
  - { role: setupKnownHosts }
  - { role: apt-get-upgrade }
  - { role: etcHosts }
  - { role: fastest_mirror }

- hosts: 'ManagementNodes:LoginNodes:DesktopNodes'
  roles:
  - { role: openLdapClient }
  - { role: ssh-password-login }
  - { role: enable_root }

- hosts: 'ManagementNodes'
  roles:
  - { role: nfs-server }
  - { role: syncExports }

- hosts: 'LoginNodes:DesktopNodes'
  roles:
  - { role: move_homedir }
  - { role: nfs-client }

- hosts: 'ManagementNodes:LoginNodes:DesktopNodes'
  roles:
  - { role: slurm-from-source }
- hosts: 'ManagementNodes'
  roles:
  - { role: slurmdb }

- hosts: '*'
  roles:
  - { role: slurm-start }

- hosts: 'ManagementNodes'
  roles:
  - { role: link_usr_local, src: /cinderVolume/local, dest: /usr/local }
  - { role: lmod }

- hosts: '*'
  roles:
  - { role: enable_lmod }

- hosts: LoginNodes
  roles:
  - { role: strudel_config }

- hosts: '*'
  roles:
  - { role: vncserver }
  - { role: jasons_ssh_ca }
  - { role: sshtunnel_user }
  - { role: MonashBioinformaticsPlatform_node_allocation }

